language: c
os: linux
dist: bionic
cache: ccache
services:
  - docker
jobs:
  include:
    - os: linux
      arch: ppc64le
      env: TR_ARCH=local
      dist: bionic
    - env: TR_ARCH=local STREAM_TEST=1
script:
  - sudo make CCACHE=1 -C scripts/travis $TR_ARCH
after_success:
  - ccache -s
  - make -C scripts/travis after_success
